set backspace=indent,eol,start  "bs:    allows you to backspace over the listed character types
set linebreak                   "lbr:   causes vim to not wrap text in the middle of a word
set wrap                        "wrap:  wraps lines by default
set paste
set nocompatible
set showmatch                   "sm:    flashes matching brackets or parentheses
set number
set ignorecase
set smarttab
set incsearch
set hlsearch
syntax on                       "syn:   syntax highlighting

set tabstop=2
set shiftwidth=2
set expandtab

set softtabstop=2

:let mapleader = "," 
map <Leader>n :set number! number?<CR>
map <Leader>l :set list! list?<CR>
map <Leader>, :NERDTreeToggle<CR>

autocmd BufRead,BufNewFile *.json setfiletype ruby
autocmd BufRead,BufNewFile *.erb setfiletype ruby
autocmd FileType ruby set tabstop=2
autocmd FileType perl set tabstop=2
autocmd FileType php set tabstop=2
autocmd FileType java set tabstop=2

let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1 

"hi Comment      ctermfg=lightgray


colorscheme slate
