set backspace=indent,eol,start  "bs:    allows you to backspace over the listed character types
set colorcolumn=80
set expandtab
set ignorecase
set hlsearch
set incsearch
set linebreak                   "lbr:   causes vim to not wrap text in the middle of a word
set nocompatible
set number
set paste
set shiftwidth=2
set showmatch                   "sm:    flashes matching brackets or parentheses
set softtabstop=2
set smarttab
set tabstop=2
set wrap                        "wrap:  wraps lines by default
syntax on                       "syn:   syntax highlighting

:let mapleader = "," 
map <Leader>n :set number! number?<CR>
map <Leader>l :set list! list?<CR>
map <Leader>, :NERDTreeToggle<CR>

autocmd BufRead,BufNewFile *.json setfiletype ruby
autocmd BufRead,BufNewFile *.erb setfiletype ruby
autocmd FileType java set tabstop=2
autocmd FileType perl set tabstop=2
autocmd FileType php set tabstop=2
autocmd FileType python set tabstop=2
autocmd FileType ruby set tabstop=2

let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1 

"hi Comment      ctermfg=lightgray

colorscheme slate
