#!/usr/bin/env bash

set -e

usage() {
  SCRIPT=$(basename $0)
  echo "usage: $SCRIPT DIR_TO_BE_BACKED_UP"
  echo "ex: $SCRIPT music"
  exit 255
}

missingDir() {
  echo "ERR: missing dir: $1"
  exit 256
}

BACKUP=$1

if [ -z $BACKUP ]; then
  usage
fi

SRC="/data/$BACKUP/"
DEST="/backup/backup/$BACKUP/"

if [ ! -d $SRC ]; then
  missingDir $SRC
fi

if [ ! -d $DEST ]; then
  missingDir $DEST
fi

if [ $(/bin/mount | /bin/grep backup | /usr/bin/wc -l) != 1 ]; then
  echo "ERR: is backup volume mounted?"
  exit 257
fi

if [ $(/usr/bin/rsync -avn --exclude='*DS_Store*' --exclude='._*' --exclude='*.jpg' $SRC $DEST | /bin/grep "\.mp3" | /usr/bin/wc -l) != 0 ]; then

  echo "cleaning up ._ files from $SRC first."
  /usr/bin/find $SRC | /bin/grep \/\._ | /bin/sed "s/'/\\\'/g" | /usr/bin/xargs -I {} rm -f {}

  echo "doing the following in 10s. speak now or forever hold your peace."
  echo "rsync -av $SRC $DEST"

  for i in {1..10}; do 
  echo -n "."
  sleep 1
  done

  echo

  /bin/chmod -R 0777 $SRC

  ( /usr/bin/rsync -av --exclude='*DS_Store*' --exclude='._*' --exclude='*.jpg' $SRC $DEST; \
    find $SRC | egrep -v '\._|DS_' > $SRC/playlist.txt; \
    sudo service ezstream stop; \
    sudo service ezstream start ) | /usr/bin/mail -s "Automated backup report" justinmhunter@gmail.com

  echo "done."
  exit 0

else

  echo "no files to rsync. exiting."

fi
